-- =========================================================
-- Migration V0.0.0: Initial Schema
-- =========================================================
-- This migration documents the initial database structure that was
-- originally created automatically by Hibernate DDL (spring.jpa.hibernate.ddl-auto).
-- 
-- Purpose: Enables Flyway-based migrations in fresh databases and provides
-- a complete schema reference for new deployments.
--
-- Note: If your database was created by Hibernate DDL, this migration will be
-- skipped by Flyway (baseline) or fail safely with IF NOT EXISTS checks.
-- =========================================================

-- =========================================================
-- SEQUENCES
-- =========================================================

-- User sequence (AUTO strategy)
CREATE SEQUENCE IF NOT EXISTS app_user_seq START WITH 1 INCREMENT BY 50;

-- Role sequence (AUTO strategy)
CREATE SEQUENCE IF NOT EXISTS role_seq START WITH 1 INCREMENT BY 50;

-- Inventory sequence (AUTO strategy)
CREATE SEQUENCE IF NOT EXISTS inventory_seq START WITH 1 INCREMENT BY 50;

-- Product variant sequence (SEQUENCE strategy)
CREATE SEQUENCE IF NOT EXISTS product_variant_seq START WITH 1 INCREMENT BY 1;

-- =========================================================
-- USER MANAGEMENT TABLES
-- =========================================================

-- Roles table
CREATE TABLE IF NOT EXISTS role (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Inventory table (must be created before app_user due to FK)
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT PRIMARY KEY
);

-- Users table
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    name VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    inventory_id BIGINT UNIQUE,
    CONSTRAINT fk_user_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

CREATE INDEX IF NOT EXISTS idx_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_user_inventory ON app_user(inventory_id);

-- Users-Roles join table
CREATE TABLE IF NOT EXISTS users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES role(id)
);

-- Refresh tokens table
CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT,
    expiry_date TIMESTAMP(6),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- =========================================================
-- PRODUCT CATALOG TABLES
-- =========================================================

-- Categories table (BEFORE V3.0.0 - global categories)
-- Note: V3.0.0 will add inventory_id column to make categories inventory-scoped
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

-- Products table (BEFORE V3.0.0 - global products)
-- Note: V3.0.0 will add inventory_id and sale_price columns
CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(255),
    color VARCHAR(255),
    img_url VARCHAR(255),
    category_id BIGINT,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX IF NOT EXISTS idx_product_model_color ON product(model, color);
CREATE INDEX IF NOT EXISTS idx_product_category ON product(category_id);

-- Product variants table
CREATE TABLE IF NOT EXISTS product_variant (
    id BIGINT PRIMARY KEY,
    sku VARCHAR(255),
    size VARCHAR(255),
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_product_variant_product FOREIGN KEY (product_id) REFERENCES product(id)
);

-- =========================================================
-- INVENTORY MANAGEMENT TABLES
-- =========================================================

-- Inventory items table
CREATE TABLE IF NOT EXISTS inventory_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantity INTEGER NOT NULL,
    average_cost DECIMAL(19,2),
    last_purchase_date DATE,
    product_variant_id BIGINT NOT NULL,
    inventory_id BIGINT NOT NULL,
    CONSTRAINT fk_inventory_item_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id),
    CONSTRAINT fk_inventory_item_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_item_variant ON inventory_item(product_variant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_item_inventory_variant ON inventory_item(inventory_id, product_variant_id);

-- Inventory catalog (public store view)
CREATE TABLE IF NOT EXISTS inventory_catalog (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    store_name VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL,
    show_stock_quantity BOOLEAN NOT NULL,
    show_price BOOLEAN NOT NULL,
    show_whatsapp_button BOOLEAN NOT NULL,
    show_size_selector BOOLEAN,
    whatsapp_number VARCHAR(255),
    primary_color VARCHAR(7),
    logo_url VARCHAR(500),
    description TEXT,
    inventory_id BIGINT UNIQUE,
    CONSTRAINT fk_inventory_catalog_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

-- Store info table
CREATE TABLE IF NOT EXISTS store_info (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inventory_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    cnpj VARCHAR(18),
    email VARCHAR(100),
    website VARCHAR(100),
    CONSTRAINT fk_store_info_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

-- =========================================================
-- PURCHASE ORDERS TABLES
-- =========================================================

-- Purchase orders table
CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_number VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'INVOICED',
    date DATE,
    total_amount DECIMAL(10,2),
    payment_method VARCHAR(50) NOT NULL,
    inventory_id BIGINT NOT NULL,
    CONSTRAINT fk_purchase_order_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_date ON purchase_order(date);
CREATE INDEX IF NOT EXISTS idx_purchase_order_inventory_date ON purchase_order(inventory_id, date);
CREATE INDEX IF NOT EXISTS idx_purchase_order_number ON purchase_order(order_number);

-- Purchase order items table
CREATE TABLE IF NOT EXISTS purchase_order_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id BIGINT,
    quantity INTEGER NOT NULL,
    purchase_price DECIMAL(10,2),
    purchase_order_id BIGINT NOT NULL,
    CONSTRAINT fk_purchase_order_item_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id),
    CONSTRAINT fk_purchase_order_item_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id)
);

-- =========================================================
-- SALES TABLES
-- =========================================================

-- Sales table
CREATE TABLE IF NOT EXISTS sale (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP(6) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    total_profit DECIMAL(12,2) NOT NULL,
    inventory_id BIGINT NOT NULL,
    CONSTRAINT fk_sale_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

CREATE INDEX IF NOT EXISTS idx_sale_date ON sale(date);
CREATE INDEX IF NOT EXISTS idx_sale_inventory_date ON sale(inventory_id, date);

-- Sale items table
CREATE TABLE IF NOT EXISTS sale_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sale_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    unit_profit DECIMAL(10,2) NOT NULL,
    total_item_price DECIMAL(10,2) NOT NULL,
    total_item_profit DECIMAL(10,2) NOT NULL,
    unit_cost DECIMAL(10,2) NOT NULL,
    total_item_cost DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sale(id),
    CONSTRAINT fk_sale_item_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
);

CREATE INDEX IF NOT EXISTS idx_sale_item_sale_id ON sale_item(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_item_variant_id ON sale_item(product_variant_id);

-- Sale payments table
CREATE TABLE IF NOT EXISTS sale_payment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sale_id BIGINT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    CONSTRAINT fk_sale_payment_sale FOREIGN KEY (sale_id) REFERENCES sale(id)
);

-- =========================================================
-- FINANCIAL TABLES
-- =========================================================

-- Accounts table
CREATE TABLE IF NOT EXISTS account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- Transactions table
CREATE TABLE IF NOT EXISTS transaction (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP(6),
    type VARCHAR(50) NOT NULL,
    detail VARCHAR(50),
    description VARCHAR(255),
    amount DECIMAL(19,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    reference VARCHAR(255),
    account_id BIGINT,
    affects_profit BOOLEAN NOT NULL DEFAULT false,
    wallet_destination BOOLEAN NOT NULL DEFAULT true,
    is_consolidated BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE INDEX IF NOT EXISTS idx_transaction_date ON transaction(date);
CREATE INDEX IF NOT EXISTS idx_transaction_account_date ON transaction(account_id, date);
CREATE INDEX IF NOT EXISTS idx_transaction_reference ON transaction(reference);
CREATE INDEX IF NOT EXISTS idx_transaction_affects_profit ON transaction(affects_profit, date);
CREATE INDEX IF NOT EXISTS idx_transaction_wallet_dest ON transaction(wallet_destination, date);
CREATE INDEX IF NOT EXISTS idx_transaction_type_detail ON transaction(type, detail);

-- =========================================================
-- INITIAL DATA
-- =========================================================

-- Insert default roles if they don't exist
INSERT INTO role (id, name)
SELECT 1, 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_USER');

INSERT INTO role (id, name)
SELECT 2, 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_ADMIN');

-- Update sequences to avoid conflicts
DO $$
BEGIN
    -- Update role sequence
    PERFORM setval('role_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM role), false);
END $$;
